name: AIPI Cobertura

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ONEDRIVE_USER_ID: ${{ secrets.ONEDRIVE_USER_ID }}
      ONEDRIVE_INPUT_INSTITUCIONAL_8H: ${{ secrets.INPUT_FOLDER_INSTITUCIONAL_8H }}
      ONEDRIVE_INPUT_JARDINES_INTEGRALES: ${{ secrets.INPUT_FOLDER_JARDINES_INTEGRALES }}
      ONEDRIVE_OUTPUT_FOLDER: ${{ secrets.OUTPUT_FOLDER }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Run process
        run: python app/report_runner.py
